apiVersion: v1
kind: Service
metadata:
  name: kibana-kibana-nodeport
  namespace: logging
spec:
  type: NodePort
  ports:
    - port: 5601               
      targetPort: 5601
      protocol: TCP
  selector:
    app.kubernetes.io/name: kibana
---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: logging-ingress
  namespace: logging
  annotations:
    # Load Balancer Name
    alb.ingress.kubernetes.io/load-balancer-name: kibana-lb-ingress
    # Ingress Core Settings
    alb.ingress.kubernetes.io/scheme: internet-facing
    alb.ingress.kubernetes.io/subnets: subnet-079d2db8dbbf45582,subnet-0d787a2d112f5c0ef
    alb.ingress.kubernetes.io/healthcheck-path: /api/status
    alb.ingress.kubernetes.io/healthcheck-port: '5601'  # Match the Kibana service port
    alb.ingress.kubernetes.io/healthcheck-protocol: HTTP
    alb.ingress.kubernetes.io/success-codes: '200-399' 
    # SSL Settings
    alb.ingress.kubernetes.io/listen-ports: '[{"HTTPS":443}, {"HTTP":80}]'
    alb.ingress.kubernetes.io/certificate-arn: arn:aws:acm:us-east-1:992382545251:certificate/fe576a42-3b76-4aba-9ad3-33253d8e3f3e
    alb.ingress.kubernetes.io/ssl-redirect: '443'
    # External DNS - For creating a Record Set in Route53
    external-dns.alpha.kubernetes.io/hostname: grafana.yoram-izilov.com
spec:
  ingressClassName: aws-ingress-class
  defaultBackend:
    service:
      name: kibana-kibana-nodeport
      port:
        number: 5601